// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.Constants;
import frc.robot.Robot;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Subsystem;

import com.ctre.phoenix.motorcontrol.*;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonFX falconLeftMaster;
    private WPI_TalonFX falconLeftFollower;
    private WPI_TalonFX falconRightMaster;
    private WPI_TalonFX falconRightFollower;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public DriveTrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        falconLeftMaster = new WPI_TalonFX(3);

        falconLeftFollower = new WPI_TalonFX(2);

        falconRightMaster = new WPI_TalonFX(1);

        falconRightFollower = new WPI_TalonFX(0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    MotionMagicArbFeedForward mmArbFeedForward;

    public void mmArbFeedForwardInit() {
        mmArbFeedForward = new MotionMagicArbFeedForward(falconLeftMaster, 
                falconLeftFollower, falconRightMaster,
                falconRightFollower, Robot.oi.joystick1);
    }

    public void mmArbFeedForward() {
        mmArbFeedForward.Periodic();
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void StopAllMotors() {
        falconLeftFollower.set(0);
        falconLeftMaster.set(0);
        falconRightMaster.set(0);
        falconLeftFollower.set(0);
    }

}
